# HOG + SVM Classifier

## Random partition

In [66]:
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
import numpy as np
from PIL import Image
import glob
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import KFold
import cv2 as cv

In [70]:
path = '/home/sueloc/Desktop/machine_learning/hog_svm-classifier/images'

dataframe = []
for filename in glob.glob(path + '/*.jpg'):
    im = cv.imread(filename)
    dataframe.append(im)

dataframe = np.array(dataframe)

In [71]:
training_data, testing_data = train_test_split(dataframe, test_size=0.2, random_state=25)

training_data = np.array(training_data)
testing_data = np.array(testing_data)

print(f"No. of training examples: {training_data.shape[0]}")
print(f"No. of testing examples: {testing_data.shape[0]}")

No. of training examples: 10526
No. of testing examples: 2632


## HOG feature vector

## Train

In [72]:
seed = 1
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
for train, test in kfold.split(dataframe):
    print('train: %s, test: %s' % (dataframe[train], dataframe[test]))

train: [[[[ 89  89  89]
   [ 56  56  56]
   [ 30  30  30]
   ...
   [141 141 141]
   [133 133 133]
   [129 129 129]]

  [[ 89  89  89]
   [ 56  56  56]
   [ 32  32  32]
   ...
   [142 142 142]
   [135 135 135]
   [129 129 129]]

  [[ 89  89  89]
   [ 56  56  56]
   [ 33  33  33]
   ...
   [143 143 143]
   [136 136 136]
   [130 130 130]]

  ...

  [[102 102 102]
   [100 100 100]
   [ 98  98  98]
   ...
   [121 121 121]
   [121 121 121]
   [123 123 123]]

  [[103 103 103]
   [100 100 100]
   [ 98  98  98]
   ...
   [121 121 121]
   [121 121 121]
   [122 122 122]]

  [[103 103 103]
   [100 100 100]
   [ 98  98  98]
   ...
   [121 121 121]
   [122 122 122]
   [122 122 122]]]


 [[[ 57  57  57]
   [ 55  55  55]
   [ 55  55  55]
   ...
   [146 146 146]
   [132 132 132]
   [115 115 115]]

  [[ 62  62  62]
   [ 59  59  59]
   [ 59  59  59]
   ...
   [142 142 142]
   [127 127 127]
   [111 111 111]]

  [[ 66  66  66]
   [ 65  65  65]
   [ 64  64  64]
   ...
   [139 139 139]
   [124 124 124]
   [